
# ANN for Regression

In [42]:
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

In [20]:
df = pd.read_csv("Real estate.csv")

In [21]:
df

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [22]:
X = df.drop(columns=['Y house price of unit area'])
y = df['Y house price of unit area']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizing the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)  
])

In [25]:
model.compile(optimizer='adam', loss='mean_squared_error', 
              metrics=['mean_squared_error', 'mean_absolute_error'])  # Adding MAE as a metric

In [26]:
history = model.fit(X_train_scaled, y_train, epochs=50, batch_size=16, validation_split=0.1)

Epoch 1/50
19/19 [==============================] - 0s 6ms/step - loss: 1608.7883 - mean_squared_error: 1608.7883 - mean_absolute_error: 37.9758 - val_loss: 2115.6287 - val_mean_squared_error: 2115.6287 - val_mean_absolute_error: 42.1965
Epoch 2/50
19/19 [==============================] - 0s 2ms/step - loss: 1532.2128 - mean_squared_error: 1532.2128 - mean_absolute_error: 36.9396 - val_loss: 2022.4146 - val_mean_squared_error: 2022.4146 - val_mean_absolute_error: 41.0727
Epoch 3/50
19/19 [==============================] - 0s 2ms/step - loss: 1441.8910 - mean_squared_error: 1441.8910 - mean_absolute_error: 35.7136 - val_loss: 1900.2448 - val_mean_squared_error: 1900.2448 - val_mean_absolute_error: 39.5628
Epoch 4/50
19/19 [==============================] - 0s 2ms/step - loss: 1319.5095 - mean_squared_error: 1319.5095 - mean_absolute_error: 33.9978 - val_loss: 1725.4839 - val_mean_squared_error: 1725.4839 - val_mean_absolute_error: 37.3652
Epoch 5/50
19/19 [==============================] - 0s 2ms/step - loss: 1148.0710 - mean_squared_error: 1148.0710 - mean_absolute_error: 31.5228 - val_loss: 1487.0706 - val_mean_squared_error: 1487.0706 - val_mean_absolute_error: 34.1820
Epoch 6/50
19/19 [==============================] - 0s 2ms/step - loss: 923.7188 - mean_squared_error: 923.7188 - mean_absolute_error: 28.0144 - val_loss: 1180.0624 - val_mean_squared_error: 1180.0624 - val_mean_absolute_error: 29.6906
Epoch 7/50
19/19 [==============================] - 0s 2ms/step - loss: 659.4058 - mean_squared_error: 659.4058 - mean_absolute_error: 23.3452 - val_loss: 837.8233 - val_mean_squared_error: 837.8233 - val_mean_absolute_error: 23.7935
Epoch 8/50
19/19 [==============================] - 0s 2ms/step - loss: 395.9201 - mean_squared_error: 395.9201 - mean_absolute_error: 17.5794 - val_loss: 536.8317 - val_mean_squared_error: 536.8317 - val_mean_absolute_error: 17.0059
Epoch 9/50
19/19 [==============================] - 0s 2ms/step - loss: 201.6442 - mean_squared_error: 201.6442 - mean_absolute_error: 11.7007 - val_loss: 350.7698 - val_mean_squared_error: 350.7698 - val_mean_absolute_error: 11.2794
Epoch 10/50
19/19 [==============================] - 0s 2ms/step - loss: 104.5595 - mean_squared_error: 104.5595 - mean_absolute_error: 8.0297 - val_loss: 280.0080 - val_mean_squared_error: 280.0080 - val_mean_absolute_error: 8.6268
Epoch 11/50
19/19 [==============================] - 0s 2ms/step - loss: 79.1314 - mean_squared_error: 79.1314 - mean_absolute_error: 6.9821 - val_loss: 256.2243 - val_mean_squared_error: 256.2243 - val_mean_absolute_error: 8.1773
Epoch 12/50
19/19 [==============================] - 0s 2ms/step - loss: 70.2364 - mean_squared_error: 70.2364 - mean_absolute_error: 6.5996 - val_loss: 244.7094 - val_mean_squared_error: 244.7094 - val_mean_absolute_error: 7.9790
Epoch 13/50
19/19 [==============================] - 0s 2ms/step - loss: 65.7145 - mean_squared_error: 65.7145 - mean_absolute_error: 6.3860 - val_loss: 236.6514 - val_mean_squared_error: 236.6514 - val_mean_absolute_error: 7.8534
Epoch 14/50
19/19 [==============================] - 0s 2ms/step - loss: 63.3114 - mean_squared_error: 63.3114 - mean_absolute_error: 6.2225 - val_loss: 232.4214 - val_mean_squared_error: 232.4214 - val_mean_absolute_error: 7.7505
Epoch 15/50
19/19 [==============================] - 0s 2ms/step - loss: 60.7552 - mean_squared_error: 60.7552 - mean_absolute_error: 6.0834 - val_loss: 225.5160 - val_mean_squared_error: 225.5160 - val_mean_absolute_error: 7.6062
Epoch 16/50
19/19 [==============================] - 0s 2ms/step - loss: 59.0326 - mean_squared_error: 59.0326 - mean_absolute_error: 5.9770 - val_loss: 221.3356 - val_mean_squared_error: 221.3356 - val_mean_absolute_error: 7.5312
Epoch 17/50
19/19 [==============================] - 0s 2ms/step - loss: 57.6843 - mean_squared_error: 57.6843 - mean_absolute_error: 5.8763 - val_loss: 218.7624 - val_mean_squared_error: 218.7624 - val_mean_absolute_error: 7.4866
Epoch 18/50
19/19 [==============================] - 0s 2ms/step - loss: 56.4514 - mean_squared_error: 56.4514 - mean_absolute_error: 5.7794 - val_loss: 215.3730 - val_mean_squared_error: 215.3730 - val_mean_absolute_error: 7.4104
Epoch 19/50
19/19 [==============================] - 0s 2ms/step - loss: 55.7063 - mean_squared_error: 55.7063 - mean_absolute_error: 5.7238 - val_loss: 212.1800 - val_mean_squared_error: 212.1800 - val_mean_absolute_error: 7.3769
Epoch 20/50
19/19 [==============================] - 0s 2ms/step - loss: 54.7553 - mean_squared_error: 54.7553 - mean_absolute_error: 5.6588 - val_loss: 210.6515 - val_mean_squared_error: 210.6515 - val_mean_absolute_error: 7.3340
Epoch 21/50
19/19 [==============================] - 0s 2ms/step - loss: 54.3150 - mean_squared_error: 54.3150 - mean_absolute_error: 5.6570 - val_loss: 206.3671 - val_mean_squared_error: 206.3671 - val_mean_absolute_error: 7.2070
Epoch 22/50
19/19 [==============================] - 0s 2ms/step - loss: 53.3683 - mean_squared_error: 53.3683 - mean_absolute_error: 5.5813 - val_loss: 206.7369 - val_mean_squared_error: 206.7369 - val_mean_absolute_error: 7.2243
Epoch 23/50
19/19 [==============================] - 0s 2ms/step - loss: 52.6550 - mean_squared_error: 52.6550 - mean_absolute_error: 5.5320 - val_loss: 205.5253 - val_mean_squared_error: 205.5253 - val_mean_absolute_error: 7.2226
Epoch 24/50
19/19 [==============================] - 0s 2ms/step - loss: 52.4838 - mean_squared_error: 52.4838 - mean_absolute_error: 5.5068 - val_loss: 203.4182 - val_mean_squared_error: 203.4182 - val_mean_absolute_error: 7.1610
Epoch 25/50
19/19 [==============================] - 0s 2ms/step - loss: 51.9334 - mean_squared_error: 51.9334 - mean_absolute_error: 5.4538 - val_loss: 204.1823 - val_mean_squared_error: 204.1823 - val_mean_absolute_error: 7.2236
Epoch 26/50
19/19 [==============================] - 0s 2ms/step - loss: 51.6740 - mean_squared_error: 51.6740 - mean_absolute_error: 5.4543 - val_loss: 200.8087 - val_mean_squared_error: 200.8087 - val_mean_absolute_error: 7.1124
Epoch 27/50
19/19 [==============================] - 0s 2ms/step - loss: 51.2628 - mean_squared_error: 51.2628 - mean_absolute_error: 5.4093 - val_loss: 201.4520 - val_mean_squared_error: 201.4520 - val_mean_absolute_error: 7.1430
Epoch 28/50
19/19 [==============================] - 0s 2ms/step - loss: 50.9182 - mean_squared_error: 50.9182 - mean_absolute_error: 5.4015 - val_loss: 201.0693 - val_mean_squared_error: 201.0693 - val_mean_absolute_error: 7.0912
Epoch 29/50
19/19 [==============================] - 0s 2ms/step - loss: 50.5248 - mean_squared_error: 50.5248 - mean_absolute_error: 5.3815 - val_loss: 200.3182 - val_mean_squared_error: 200.3182 - val_mean_absolute_error: 7.0708
Epoch 30/50
19/19 [==============================] - 0s 2ms/step - loss: 50.0983 - mean_squared_error: 50.0983 - mean_absolute_error: 5.3254 - val_loss: 200.5698 - val_mean_squared_error: 200.5698 - val_mean_absolute_error: 7.0676
Epoch 31/50
19/19 [==============================] - 0s 2ms/step - loss: 50.0117 - mean_squared_error: 50.0117 - mean_absolute_error: 5.3014 - val_loss: 200.6548 - val_mean_squared_error: 200.6548 - val_mean_absolute_error: 7.0671
Epoch 32/50
19/19 [==============================] - 0s 2ms/step - loss: 49.7127 - mean_squared_error: 49.7127 - mean_absolute_error: 5.3022 - val_loss: 197.4639 - val_mean_squared_error: 197.4639 - val_mean_absolute_error: 6.9829
Epoch 33/50
19/19 [==============================] - 0s 2ms/step - loss: 49.6542 - mean_squared_error: 49.6542 - mean_absolute_error: 5.3082 - val_loss: 197.3045 - val_mean_squared_error: 197.3045 - val_mean_absolute_error: 6.9909
Epoch 34/50
19/19 [==============================] - 0s 2ms/step - loss: 49.2401 - mean_squared_error: 49.2401 - mean_absolute_error: 5.2637 - val_loss: 198.1598 - val_mean_squared_error: 198.1598 - val_mean_absolute_error: 7.0169
Epoch 35/50
19/19 [==============================] - 0s 2ms/step - loss: 48.9516 - mean_squared_error: 48.9516 - mean_absolute_error: 5.2375 - val_loss: 197.5025 - val_mean_squared_error: 197.5025 - val_mean_absolute_error: 6.9745
Epoch 36/50
19/19 [==============================] - 0s 2ms/step - loss: 48.8885 - mean_squared_error: 48.8885 - mean_absolute_error: 5.2331 - val_loss: 195.9016 - val_mean_squared_error: 195.9016 - val_mean_absolute_error: 6.9087
Epoch 37/50
19/19 [==============================] - 0s 2ms/step - loss: 48.7994 - mean_squared_error: 48.7994 - mean_absolute_error: 5.2195 - val_loss: 196.3235 - val_mean_squared_error: 196.3235 - val_mean_absolute_error: 6.9166
Epoch 38/50
19/19 [==============================] - 0s 2ms/step - loss: 48.5756 - mean_squared_error: 48.5756 - mean_absolute_error: 5.2065 - val_loss: 195.6575 - val_mean_squared_error: 195.6575 - val_mean_absolute_error: 6.9036
Epoch 39/50
19/19 [==============================] - 0s 2ms/step - loss: 48.4247 - mean_squared_error: 48.4247 - mean_absolute_error: 5.1965 - val_loss: 196.7564 - val_mean_squared_error: 196.7564 - val_mean_absolute_error: 6.9049
Epoch 40/50
19/19 [==============================] - 0s 2ms/step - loss: 48.2301 - mean_squared_error: 48.2301 - mean_absolute_error: 5.1887 - val_loss: 195.5298 - val_mean_squared_error: 195.5298 - val_mean_absolute_error: 6.8846
Epoch 41/50
19/19 [==============================] - 0s 2ms/step - loss: 48.0424 - mean_squared_error: 48.0424 - mean_absolute_error: 5.1890 - val_loss: 192.7053 - val_mean_squared_error: 192.7053 - val_mean_absolute_error: 6.7978
Epoch 42/50
19/19 [==============================] - 0s 2ms/step - loss: 47.8727 - mean_squared_error: 47.8727 - mean_absolute_error: 5.1658 - val_loss: 195.8719 - val_mean_squared_error: 195.8719 - val_mean_absolute_error: 6.9189
Epoch 43/50
19/19 [==============================] - 0s 2ms/step - loss: 47.5914 - mean_squared_error: 47.5914 - mean_absolute_error: 5.1251 - val_loss: 195.3815 - val_mean_squared_error: 195.3815 - val_mean_absolute_error: 6.8502
Epoch 44/50
19/19 [==============================] - 0s 2ms/step - loss: 47.5032 - mean_squared_error: 47.5032 - mean_absolute_error: 5.1305 - val_loss: 193.7148 - val_mean_squared_error: 193.7148 - val_mean_absolute_error: 6.8395
Epoch 45/50
19/19 [==============================] - 0s 2ms/step - loss: 47.3782 - mean_squared_error: 47.3782 - mean_absolute_error: 5.1242 - val_loss: 195.3669 - val_mean_squared_error: 195.3669 - val_mean_absolute_error: 6.8580
Epoch 46/50
19/19 [==============================] - 0s 2ms/step - loss: 47.2869 - mean_squared_error: 47.2869 - mean_absolute_error: 5.1096 - val_loss: 193.2205 - val_mean_squared_error: 193.2205 - val_mean_absolute_error: 6.7881
Epoch 47/50
19/19 [==============================] - 0s 2ms/step - loss: 47.1440 - mean_squared_error: 47.1440 - mean_absolute_error: 5.1013 - val_loss: 194.2412 - val_mean_squared_error: 194.2412 - val_mean_absolute_error: 6.8131
Epoch 48/50
19/19 [==============================] - 0s 2ms/step - loss: 46.7931 - mean_squared_error: 46.7931 - mean_absolute_error: 5.0724 - val_loss: 191.1103 - val_mean_squared_error: 191.1103 - val_mean_absolute_error: 6.7077
Epoch 49/50
19/19 [==============================] - 0s 2ms/step - loss: 47.0194 - mean_squared_error: 47.0194 - mean_absolute_error: 5.0773 - val_loss: 193.2030 - val_mean_squared_error: 193.2030 - val_mean_absolute_error: 6.7393
Epoch 50/50
19/19 [==============================] - 0s 2ms/step - loss: 46.7108 - mean_squared_error: 46.7108 - mean_absolute_error: 5.0751 - val_loss: 190.8470 - val_mean_squared_error: 190.8470 - val_mean_absolute_error: 6.7117

In [27]:
mse, _, mae = model.evaluate(X_test_scaled, y_test)  
print("Mean Squared Error on Test Set:", mse)
print("Mean Absolute Error on Test Set:", mae)

3/3 [==============================] - 0s 1ms/step - loss: 53.6931 - mean_squared_error: 53.6931 - mean_absolute_error: 5.3885
Mean Squared Error on Test Set: 53.693058013916016
Mean Absolute Error on Test Set: 5.3885297775268555

In [28]:
rmse = np.sqrt(mse)
print("Root Mean Squared Error on Test Set:", rmse)

# Predictions
predictions = model.predict(X_test_scaled)

Root Mean Squared Error on Test Set: 7.327554709036025
3/3 [==============================] - 0s 2ms/step

# ANN for Classification

In [29]:
df=pd.read_csv("data.csv")
df

,process.b1.capacity,process.b2.capacity,process.b3.capacity,process.b4.capacity,property.price,property.product,property.winner,verification.result,verification.time
0,0,0,2,1,59,1,0,False,163.316667
1,0,0,2,1,59,2,0,False,200.860000
2,0,0,2,1,59,4,0,False,154.888889
3,0,0,2,1,59,6,0,False,108.640000
4,0,0,2,1,60,1,0,True,85.466667
...,...,...,...,...,...,...,...,...,...
2038,2,3,2,1,90,5,0,True,82.425000
2039,2,3,2,1,90,5,1,True,1316.983333
2040,2,3,2,1,90,5,2,False,9365.450000
2041,2,3,2,1,90,5,3,False,8474.025000
2042,2,3,2,1,90,5,4,True,82.008333

In [30]:
X=df.drop(columns=['verification.result'])
X

,process.b1.capacity,process.b2.capacity,process.b3.capacity,process.b4.capacity,property.price,property.product,property.winner,verification.time
0,0,0,2,1,59,1,0,163.316667
1,0,0,2,1,59,2,0,200.860000
2,0,0,2,1,59,4,0,154.888889
3,0,0,2,1,59,6,0,108.640000
4,0,0,2,1,60,1,0,85.466667
...,...,...,...,...,...,...,...,...
2038,2,3,2,1,90,5,0,82.425000
2039,2,3,2,1,90,5,1,1316.983333
2040,2,3,2,1,90,5,2,9365.450000
2041,2,3,2,1,90,5,3,8474.025000
2042,2,3,2,1,90,5,4,82.008333

In [31]:
Y=df['verification.result']
Y_encoded = tf.keras.utils.to_categorical(Y,num_classes=2)

In [32]:
x_train,x_test,y_train,y_test=train_test_split(X,Y_encoded,test_size=0.2,random_state=42)

In [36]:
model=Sequential()
model.add(Dense(8, input_dim=8,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(2,activation='softmax'))

In [37]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=10)

# Evaluate the model
loss, accuracy = model.evaluate(x_test, y_test)
print('Accuracy:', accuracy)

Epoch 1/10
164/164 [==============================] - 0s 652us/step - loss: 12.4630 - accuracy: 0.8935
Epoch 2/10
164/164 [==============================] - 0s 649us/step - loss: 1.8884 - accuracy: 0.8703
Epoch 3/10
164/164 [==============================] - 0s 649us/step - loss: 2.1575 - accuracy: 0.9229
Epoch 4/10
164/164 [==============================] - 0s 655us/step - loss: 1.4665 - accuracy: 0.8941
Epoch 5/10
164/164 [==============================] - 0s 649us/step - loss: 1.2565 - accuracy: 0.8880
Epoch 6/10
164/164 [==============================] - 0s 642us/step - loss: 1.3375 - accuracy: 0.9174
Epoch 7/10
164/164 [==============================] - 0s 655us/step - loss: 1.0268 - accuracy: 0.9186
Epoch 8/10
164/164 [==============================] - 0s 642us/step - loss: 1.4953 - accuracy: 0.8972
Epoch 9/10
164/164 [==============================] - 0s 661us/step - loss: 0.8603 - accuracy: 0.9119
Epoch 10/10
164/164 [==============================] - 0s 661us/step - loss: 1.5654 - accuracy: 0.9131
13/13 [==============================] - 0s 831us/step - loss: 1.4530 - accuracy: 0.9046
Accuracy: 0.9046455025672913

In [40]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions

# Generate classification report
print(classification_report(y_test, y_pred))

13/13 [==============================] - 0s 748us/step
              precision    recall  f1-score   support

           0       0.92      0.98      0.95       354
           1       0.77      0.42      0.54        55

   micro avg       0.90      0.90      0.90       409
   macro avg       0.84      0.70      0.74       409
weighted avg       0.90      0.90      0.89       409
 samples avg       0.90      0.90      0.90       409

# ANN for Classification using Dropout

In [43]:
model = Sequential()
model.add(Dense(8, input_dim=8, activation='relu'))
model.add(Dropout(0.2))  # Adding dropout with rate 0.2
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.2))  # Adding dropout with rate 0.2
model.add(Dense(2, activation='softmax'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=10)

Epoch 1/10
164/164 [==============================] - 0s 685us/step - loss: 75.3184 - accuracy: 0.8164
Epoch 2/10
164/164 [==============================] - 0s 655us/step - loss: 38.8024 - accuracy: 0.8360
Epoch 3/10
164/164 [==============================] - 0s 667us/step - loss: 23.8419 - accuracy: 0.8348
Epoch 4/10
164/164 [==============================] - 0s 667us/step - loss: 17.2181 - accuracy: 0.8647
Epoch 5/10
164/164 [==============================] - 0s 734us/step - loss: 10.7607 - accuracy: 0.8739
Epoch 6/10
164/164 [==============================] - 0s 685us/step - loss: 9.8835 - accuracy: 0.8641
Epoch 7/10
164/164 [==============================] - 0s 704us/step - loss: 6.8098 - accuracy: 0.8696
Epoch 8/10
164/164 [==============================] - 0s 704us/step - loss: 6.0118 - accuracy: 0.8770
Epoch 9/10
164/164 [==============================] - 0s 698us/step - loss: 3.7404 - accuracy: 0.8684
Epoch 10/10
164/164 [==============================] - 0s 673us/step - loss: 3.0109 - accuracy: 0.8464

In [44]:
loss, accuracy = model.evaluate(x_test, y_test)
print('Accuracy:', accuracy)

# Generate classification report
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions
print(classification_report(y_test, y_pred))

13/13 [==============================] - 0s 915us/step - loss: 1.2178 - accuracy: 0.9022
Accuracy: 0.90220046043396
13/13 [==============================] - 0s 661us/step
              precision    recall  f1-score   support

           0       0.92      0.97      0.95       354
           1       0.73      0.44      0.55        55

   micro avg       0.90      0.90      0.90       409
   macro avg       0.82      0.71      0.75       409
weighted avg       0.89      0.90      0.89       409
 samples avg       0.90      0.90      0.90       409

#  ANN for Classification using L1 L2 regularization

In [45]:
from keras import regularizers
model = Sequential()
model.add(Dense(8, input_dim=8, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=0.01, l2=0.01)))
model.add(Dense(16, activation='relu', kernel_regularizer=regularizers.l1_l2(l1=0.01, l2=0.01)))
model.add(Dense(2, activation='softmax'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=10)

Epoch 1/10
164/164 [==============================] - 0s 667us/step - loss: 101.5685 - accuracy: 0.7252
Epoch 2/10
164/164 [==============================] - 0s 661us/step - loss: 2.4501 - accuracy: 0.9100
Epoch 3/10
164/164 [==============================] - 0s 649us/step - loss: 2.0388 - accuracy: 0.8874
Epoch 4/10
164/164 [==============================] - 0s 655us/step - loss: 1.7297 - accuracy: 0.9064
Epoch 5/10
164/164 [==============================] - 0s 673us/step - loss: 1.4911 - accuracy: 0.9088
Epoch 6/10
164/164 [==============================] - 0s 649us/step - loss: 1.2985 - accuracy: 0.9033
Epoch 7/10
164/164 [==============================] - 0s 661us/step - loss: 1.4304 - accuracy: 0.9039
Epoch 8/10
164/164 [==============================] - 0s 655us/step - loss: 1.4945 - accuracy: 0.9137
Epoch 9/10
164/164 [==============================] - 0s 679us/step - loss: 1.5655 - accuracy: 0.9064
Epoch 10/10
164/164 [==============================] - 0s 691us/step - loss: 2.0289 - accuracy: 0.8837

In [46]:
loss, accuracy = model.evaluate(x_test, y_test)
print('Accuracy:', accuracy)

# Generate classification report
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions
print(classification_report(y_test, y_pred))

13/13 [==============================] - 0s 831us/step - loss: 1.3915 - accuracy: 0.9120
Accuracy: 0.9119804501533508
13/13 [==============================] - 0s 708us/step
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       354
           1       0.74      0.53      0.62        55

   micro avg       0.91      0.91      0.91       409
   macro avg       0.84      0.75      0.78       409
weighted avg       0.90      0.91      0.91       409
 samples avg       0.91      0.91      0.91       409